version: '2.3'
services:
  central:
    image: ghcr.io/takpika/mcai-central:latest
  client01:
    image: ghcr.io/takpika/mcai-client:latest
    depends_on:
      - central
      - learn
      - server
  client02:
    image: ghcr.io/takpika/mcai-client:latest
    depends_on:
      - central
      - learn
      - server
  learn:
    image: ghcr.io/takpika/mcai-learn:latest
    #image: ghcr.io/takpika/mcai-learn-gpu:latest # for GPU
    volumes:
      - ./models:/var/mcai/models
    depends_on:
      - central
    #deploy: # for GPU
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
  server:
    image: ghcr.io/takpika/mcai-server:latest
    volumes:
      - ./world:/var/mcai/world
      - ./server:/var/mcai/server
    ports:
      - "25565:25565"
    depends_on:
      - central