name: Build container images
on:
  push:
    branches:
      - development

env:
  DOCKER_TAG: "dev-${COMMITID}"

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    # 複数のDockerfileが配置されたディレクトリを列挙
    strategy:
      matrix:
        target: ["central", "client", "server", "learn", "learn-gpu"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag for master
        if: github.ref == 'refs/heads/master'
        run: |
          COMMITID=$(git rev-parse --short ${{ github.sha }})
          echo "DOCKER_TAG=development-${COMMITID}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./modules/${{ matrix.target }}
          push: true
          tags: ghcr.io/takpika/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }}