name: Build container images
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    # 複数のDockerfileが配置されたディレクトリを列挙
    strategy:
      matrix:
        target: ["central", "client", "server", "learn", "learn-gpu"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag for master
        run: |
          COMMITID=$(git rev-parse --short ${{ github.sha }})
          if [ "${{ github.base_ref }}" = "" ]; then
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          else
            BRANCH_NAME=${{ github.base_ref }}
            echo "BRANCH_NAME=${{ github.base_ref }}" >> $GITHUB_ENV
          fi
          if [ "${BRANCH_NAME}" = "development" ]; then
            echo "DOCKER_TAG=dev-${COMMITID}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${COMMITID}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t ghcr.io/${{ github.repository_owner }}/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }} --build-arg BRANCH="${{ env.BRANCH_NAME }}" ./modules/${{ matrix.target }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }}
          if [ "${{ env.BRANCH_NAME }}" = "development" ]; then
            docker tag ghcr.io/${{ github.repository_owner }}/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }} ghcr.io/${{ github.repository_owner }}/mcai-${{ matrix.target }}:latest-dev
            docker push ghcr.io/${{ github.repository_owner }}/mcai-${{ matrix.target }}:latest-dev
          else
            docker tag ghcr.io/${{ github.repository_owner }}/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }} ghcr.io/${{ github.repository_owner }}/mcai-${{ matrix.target }}:latest
            docker push ghcr.io/${{ github.repository_owner }}/mcai-${{ matrix.target }}:latest
          fi