name: Build container images
on:
  push:
    branches:
      - development

env:
  BRANCH=development

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    # 複数のDockerfileが配置されたディレクトリを列挙
    strategy:
      matrix:
        target: ["central", "client", "server", "learn", "learn-gpu"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag for master
        run: |
          COMMITID=$(git rev-parse --short ${{ github.sha }})
          if [ "${{ env.BRANCH }}" = "development" ]; then
            echo "DOCKER_TAG=dev-${COMMITID}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${COMMITID}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: |
          docker build ./modules/${{ matrix.target }} -t ghcr.io/takpika/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }} --build_arg BRANCH="${{ env.BRANCH }}"

      - name: Push Docker Image
        run: |
          docker push ghcr.io/takpika/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }}
          if [ "${{ env.BRANCH }}" = "development" ]; then
            docker tag ghcr.io/takpika/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }} ghcr.io/takpika/mcai-${{ matrix.target }}:latest-dev
            docker push ghcr.io/takpika/mcai-${{ matrix.target }}:latest-dev
          else
            docker tag ghcr.io/takpika/mcai-${{ matrix.target }}:${{ env.DOCKER_TAG }} ghcr.io/takpika/mcai-${{ matrix.target }}:latest
            docker push ghcr.io/takpika/mcai-${{ matrix.target }}:latest
          fi